#!/usr/bin/env bash

binary_main="${1}"
variable="${2}"
file_variables="${3}"
config_files="${4}"

trap_command() {
	tmux kill-session -t "${binary_main}"
}
trap trap_command SIGINT SIGTSTP SIGTERM SIGKILL EXIT
input=$(whiptail --title "${binary_main}" --inputbox "${variable}" 8 75 3>&1 1>&2 2>&3)
sed -i "s~${variable}~${variable}=${input}~" "./${file_variables}"
sed -i "s~${variable}~${input}~g" ./${config_files}/*
