#!/usr/bin/env bash

# Just run :).

verify_privileges() {
        if [ ${UID} -eq 0 ]; then
                echo -e "ERROR: Run this program without privileges!\nExiting..."
                exit 1
        fi
}

print_usage() {
        echo -e "Run:\n\t./$(basename ${0})"
}

verify_privileges

[ ${#} -ge 1 -o "${1,,}" = '-h' -o "${1,,}" = '--help' ] && {
        print_usage
        exit 1
}

# >>>>> PROGRAM START <<<<<

x-www-browser 'https://translate.google.com/?sl=en&tl=pt&text=9223372036854775808&op=translate'
sleep 5
for zkt in $(seq 7); do
	xdotool key --delay 250 Tab
done
xdotool key --delay 250 Return
